[project]
name = "sf-school-lunches"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cvxpy>=1.8.1",
    "geopandas>=1.1.2",
    "matplotlib>=3.10.8",
    "pyogrio>=0.12.1",
    "requests>=2.32.5",
]
